AllCops:
  DisplayCopNames: true
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'front/**/*'

Metrics/BlockLength:
  Exclude:
    - config/**/*.rb
    - lib/tasks/**/*.rake
    - spec/**/*.rb
    - '**/Gemfile'

Metrics/LineLength:
  Max: 130
  AllowURI: true
    - http
    - https
  Exclude:
    - config/**/*

Style/Documentation:
  Enabled: false

Naming/FileName:
  Exclude:
    - '**/Gemfile'
    - '**/Rakefile'

Style/AsciiComments:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Max: 20

Metrics/AbcSize:
  Max: 25

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

Style/FormatStringToken:
  Enabled: false
