version: '2.0'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - 3306:3306
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
volumes:
  bundle-data:
    driver: local
